name: profile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.2.1
  intl: ^0.19.0
  logging: ^1.2.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.11
  flutter_bloc:
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  introduction_screen: ^3.1.14
  shared_preferences: ^2.3.2
  http: ^1.2.2
  smooth_page_indicator: ^1.2.0+3
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/images/logo.png
    - assets/images/iisma.png
    - assets/images/iisma_detail.png
    - assets/images/polines1.jpg
    - assets/images/polines2.jpg
    - assets/images/polines3.jpg
    - assets/images/polines4.jpg
    - assets/images/logo_polines.png
    - assets/images/logo_undip.png
    - assets/images/logo_polkesmar.png
    - assets/images/logo_unnes.png
